package protoc

var allTemplates = []string{
	file,
	body,
	structLike,
	structLikeFastRead,
	structLikeFastReadField,
}

/*
 * .PkgName
 * .Imports
 * .body
 */
const file = `
{{define "file"}}
// Code generated by Kitex {{Version}}. DO NOT EDIT.

package {{.PkgName}}

import (
	"errors"
	"fmt"

	"github.com/cloudwego/kitex/pkg/protocol/bprotoc"
	{{- range $path, $alias := .Imports}}
	{{$alias }}"{{$path}}"
	{{- end}}
)

{{template "body" .}}

{{end}}{{/* define "file" */}}
`

/*
 * .Scope.StructLikes
 * .StructLikes
 */
const body = `
{{define "body"}}

{{- range .Scope.StructLikes}}
{{template "StructLikes" .}}
{{- end}}

{{- end}}{{/* define "body" */}}
`

const structLike = `
{{define "StructLikes"}}
{{template "StructLikeFastRead" .}}

{{template "StructLikeFastReadField" .}}
{{- end}}{{/* define "StructLikes" */}}
`

//
//const structLike = `
//{{define "StructLikes"}}
//{{template "StructLikeFastRead" .}}
//
//{{template "StructLikeFastReadField" .}}
//
//{{template "StructLikeFastWrite" .}}
//
//{{template "StructLikeFastWriteField" .}}
//
//{{template "StructLikeLength" .}}
//
//{{template "StructLikeLengthField" .}}
//{{- end}}{{/* define "StructLikes" */}}
//`

const structLikeFastRead = `
{{define "StructLikeFastRead"}}
{{- $TypeName := .GoName}}
func (x *{{$TypeName}}) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {

	switch number {
	{{- range .Fields}}
	case {{.ID}}:
		offset, err = x.FastReadField{{Str .ID}}(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	{{- end}}{{/* range .Fields */}}
	default:
		offset, err = bprotoc.Binary.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, errors.New("cannot parse invalid wire-format data")
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_Request[number], err)
}
{{- end}}{{/* define "StructLikeFastRead" */}}
`

const structLikeFastReadField = `
{{define "StructLikeFastReadField"}}
{{- end}}{{/* define "StructLikeFastReadField" */}}
`

//const structLikeFastReadField = `
//{{define "StructLikeFastReadField"}}
//{{- $TypeName := .GoName}}
//{{- range .Fields}}
//{{$FieldName := .GoName}}
//func (p *{{$TypeName}}) FastReadField{{Str .ID}}(buf []byte) (int, error) {
//	offset := 0
//	{{- $ctx := MkRWCtx .}}
//	{{ template "FieldFastRead" $ctx}}
//	return offset, nil
//}
//{{- end}}{{/* range .Fields */}}
//{{- end}}{{/* define "StructLikeFastReadField" */}}
//`
